main/urls.py
from django.urls import path

from .views import (
    Home,
    JSON,
    Search,
    MediaFileView,
    MediaFileDelete,
    MediaFileAdd,
    CategoriesView,
    CategoryDelete,
    PlaylistsView,
    PlaylistDelete,
    PlaylistView
)

app_name = 'main'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('search/', Search.as_view(), name='search'),
    path('json/', JSON.as_view(), name='json'),
    path('mediafile/<int:file_id>/delete', MediaFileDelete.as_view(), name='file_delete'),
    path('mediafile/<int:file_id>', MediaFileView.as_view(), name='file_view'),
    path('mediafile/add', MediaFileAdd.as_view(), name='file_add'),
    path('categories', CategoriesView.as_view(), name='categories_view'),
    path('categories/<int:cat_id>/delete', CategoryDelete.as_view(), name='category_delete'),
    path('playlists', PlaylistsView.as_view(), name='playlists_view'),
    path('playlist/<int:playlist_id>/delete', PlaylistDelete.as_view(), name='playlist_delete'),
    path('playlist/<int:playlist_id>', PlaylistView.as_view(), name='playlist_view'),

]

organiser/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import os
from django.db import models

'''
    Models for MediaFile, Category, Playlist and PlaylistMediaFile
    PlaylistMediaFile is a through table for MediaFile and Playlist
    The ordinal field would be used to allow different ordering for each MediaFile per Playlist (Not implemented yet)
'''

class MediaFile(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to="file", null=True)
    thumbnail = models.ImageField(upload_to="thumbnail")
    comment = models.TextField()

    def __str__(self):
        return self.name

    # Filename and Filetype are shortcut methods 
    def filename(self):
        return os.path.splitext(self.file.name)[0].strip("file/")

    def filetype(self):
        return os.path.splitext(self.file.name)[1].strip(".")

    def to_json(self):

        return {
            "id": self.id,
            "name": self.name,
            "file": self.filename(),
            "thumbnail": self.thumbnail.url,
            "comment": self.comment,
        }

class Category(models.Model):
    name = models.CharField(max_length=255)
    files = models.ManyToManyField(MediaFile, related_name="categories")

    def __str__(self):
        return self.name

    def to_json(self):

        return {
            "id": self.id,
            "name": self.name,
            "files": [file.id for file in self.files.all()],
        }


class Playlist(models.Model):
    name = models.CharField(max_length=255)
    files = models.ManyToManyField(MediaFile, through="PlaylistMediaFile")

    def __str__(self):
        return self.name

    def to_json(self):

        return {
            "id": self.id,
            "name": self.name,
            "files": [file.id for file in self.files.all()],
        }

    def to_json_full(self):

        return {
            "id": self.id,
            "name": self.name,
            "files": [file.to_json() for file in self.files.all()],
        }


class PlaylistMediaFile(models.Model):
    mediaFile = models.ForeignKey(MediaFile, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    ordinal = models.IntegerField(null=True)
    
    def __str__(self):
        return self.mediaFile.name

main/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import JsonResponse

from .models import MediaFile, Category, Playlist

import json

class Home(View):

    # Get homepage
    def get(self, request):

        files = MediaFile.objects.all()

        ctx = {
            'files': files
        }

        return render(request, 'home.html', context=ctx)


class Search(View):

    def get(self, request, **kwargs):

        search_query = request.GET.get("q", "")
        files = MediaFile.objects.filter(name__contains=search_query)

        ctx = {
            'files': files
        }

        return render(request, 'home.html', context=ctx)

        
class JSON(View):

    # Downloading the JSON file
    def get(self, request):

        data = {}

        # Get all the media files
        mediafiles = MediaFile.objects.all()
        data["mediafiles"] = [file.to_json() for file in mediafiles]

        # Get all the Categories:
        categories = Category.objects.all()
        data["categories"] = [category.to_json() for category in categories]

        # Get all the Playlists:
        playlists = Playlist.objects.all()
        data["playlists"] = [playlist.to_json() for playlist in playlists]

        with open("data.json", "w") as out:
            print(json.dumps(data))
            out.write(json.dumps(data))

        return redirect('main:home')

    # Uploading the JSON file
    def post(self, request):

        # Get and process the json data
        data = request.FILES.get("upload").file.read().decode('utf8')
        data = json.loads(data)

        mediafile_ids = []
        # Update Mediafiles: name and comment
        for m in data.get("mediafiles", ""):
            mediafile_ids.append(m.get("id", ""))
            file = MediaFile.objects.filter(id=m.get("id", "")).first()
            # Can only update Media Files, not create them
            if file:
                file.name = m.get("name", "")
                file.comment = m.get("comment", "")
                file.save()

        # Delete mediafiles that aren't in the json
        MediaFile.objects.exclude(id__in=mediafile_ids).delete()
        
        category_ids = []
        # Update Categories: name and MediaFiles
        for c in data.get("categories", ""):
            category_ids.append(c.get("id", ""))
            cat = Category.objects.filter(id=c.get("id", "")).first()
            # If the Catgory exists, update it
            if cat:
                cat.name = c.get("name", "")
                # Reset all the relationships with MediaFiles
                cat.files.clear()
            # Else, create it
            else:
                cat = Category.objects.create(name=c.get("name", ""))
                category_ids.append(cat.id)
            files = MediaFile.objects.filter(id__in=c.get("files", ""))
            cat.files.add(*files)
            cat.save()
            
        # Delete categories that aren't in the json
        Category.objects.exclude(id__in=category_ids).delete()

        playlist_ids = [] 
        # Update Playlists: name and MediaFiles
        for p in data.get("playlists", ""):
            playlist_ids.append(p.get("id", ""))
            playlist = Playlist.objects.filter(id=p.get("id", "")).first()
            # If the Playlist exists, update it
            if playlist:
                playlist.name = p["name"]
             # Reset all the relationships with MediaFiles
                playlist.files.clear()
            # Else, create it
            else:
                playlist = Playlist.objects.create(name=p.get("name", ""))
                playlist_ids.append(playlist.id)
            files = MediaFile.objects.filter(id__in=p.get("files", ""))
            playlist.files.add(*files)
            playlist.save()
        # Delete playlists that aren't in the json
        Playlist.objects.exclude(id__in=playlist_ids).delete()

        return JsonResponse({'success':True})

        ctx = {
            'files': files
        }

        return render(request, 'home.html', context=ctx)

class MediaFileView(View):

    # Getting the Media File page
    def get(self, request, file_id, **kwargs):

        file = MediaFile.objects.get(id=file_id)
        categories = Category.objects.all()

        ctx = {
            'file': file,
            'categories': categories,
        }

        return render(request, 'file_view.html', context=ctx)

    # Updating the Media File
    def post(self, request, file_id, **kwargs):

        file = MediaFile.objects.get(id=file_id)
        categories = Category.objects.all()

        # Update name and comment
        file.name = request.POST["name"]
        file.comment = request.POST["comment"]

        # Go through the Category checkboxes and update
        for f, v in request.POST.items():
            if "checkbox" in f:
                cat_id = f.split("-")[1]
                category = Category.objects.get(id=cat_id)
                if v != "":
                    file.categories.add(category)
                else:
                    file.categories.remove(category)

        # If a thumbnail and file have been uploaded, update them
        if request.FILES.get("file", "") != "":
            file.file = request.FILES["file"]

        if request.FILES.get("thumbnail", "") != "":
            file.thumbnail = request.FILES["thumbnail"]

        file.save()

        ctx = {
            'file': file,
            'categories': categories,
            'saved': True
        }

        return render(request, 'file_view.html', ctx)


class MediaFileAdd(View):

    # Get the create new Media File page
    def get(self, request, **kwargs):

        categories = Category.objects.all()

        ctx = {
            'categories': categories
        }

        return render(request, 'file_add.html', context=ctx)

    # Create the new Media File with the data given  
    def post(self, request, **kwargs):

        file = MediaFile.objects.create(
            name=request.POST["name"],
            comment=request.POST["comment"],
        )

        # Go through the category checkboxes
        for f, v in request.POST.items():
            if "checkbox" in f:
                cat_name = f.split("-")[1]
                category = Category.objects.get(name=cat_name)
                if v != "":
                    file.categories.add(category)

        # Thumbnail and file
        if request.FILES.get("file", "") != "":
            file.file = request.FILES["file"]

        if request.FILES.get("thumbnail", "") != "":
            file.thumbnail = request.FILES["thumbnail"]

        file.save()

        ctx = {
            'file': file,
        }

        return redirect('main:file_view', file_id=file.id)


class MediaFileDelete(View):

    # Get the delete confirmation page
    def get(self, request, file_id, **kwargs):

        file = MediaFile.objects.get(id=file_id)

        ctx = {
            'file': file
        }

        return render(request, 'file_delete.html', context=ctx)

    # Delete the Media File
    def post(self, request, file_id, **kwargs):

        file = MediaFile.objects.filter(id=file_id).delete()

        return redirect('main:home')


class CategoriesView(View):

    # Get the Categories page
    def get(self, request, **kwargs):

        categories = Category.objects.all()

        ctx = {
            'categories': categories,
        }

        return render(request, 'categories_view.html', context=ctx)

    # Create a new Category
    def post(self, request, **kwargs):

        # If the Category doesn't already exist, create it
        new_name = request.POST["category"]
        category = Category.objects.filter(name=new_name)
        if not category.count():
            Category.objects.create(name=new_name)

        categories = Category.objects.all()

        ctx = {
            'categories': categories,
        }

        return render(request, 'categories_view.html', context=ctx)


class CategoryDelete(View):

    # Get the Category delete confirmation page
    def get(self, request, cat_id, **kwargs):

        category = Category.objects.get(id=cat_id)

        ctx = {
            'category': category,
        }

        return render(request, 'category_delete.html', context=ctx)

    # Delete the Category
    def post(self, request, cat_id, **kwargs):

        category = Category.objects.get(id=cat_id)
        category.delete()

        return redirect('main:categories_view')
        

class PlaylistsView(View):

    # Get the Playlists page
    def get(self, request, **kwargs):

        playlists = Playlist.objects.all()

        # Get the data for the playlists and store it in json for vue to access
        playlist_data = {}

        for playlist in playlists:
            files = playlist.files.all()
            playlist_data[playlist.name] = playlist.to_json_full()

        ctx = {
            "playlist_data": playlist_data,
        }

        return render(request, 'playlists_view.html', context=ctx)
    
    # Create a new Playlist
    def post(self, request, **kwargs):

        # If the playlist doesn't already exist, create it
        new_name = request.POST.get("playlist", "")
        playlist = Playlist.objects.filter(name=new_name)
        if not playlist.count():
            Playlist.objects.create(name=new_name)

        playlists = Playlist.objects.all()

        ctx = {
            'playlists': playlists,
        }

        return redirect('main:playlists_view')


class PlaylistView(View):

    # Get the page for a Playlist
    def get(self, request, playlist_id, **kwargs):

        playlist = Playlist.objects.get(id=playlist_id)
        mediaFiles = MediaFile.objects.all()

        ctx = {
            'playlist': playlist,
            'mediaFiles': mediaFiles
        }

        return render(request, 'playlist_view.html', context=ctx)

    def post(self, request, playlist_id, **kwargs):

main/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <title>{% block title %}My Title{% endblock %}</title>
    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!-- Fontawesome -->
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <!-- Base Styles -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.jpg' %}"/>
    
    {% block css %}
    {% endblock css %}
</head>
<body>
    <div class="row" id="topbar">
        {% block topbar %}
        {% endblock topbar %}
    </div>
    <div class="wrapper">
        <div id="body-container" class="row">
            <div class="col col-12">
                {% block main %}
                {% endblock main %}
            </div>
        </div>
    </div>

</body>

<script>
    var json_upload_url = "{% url 'main:json' %}"
    var token = '{{csrf_token}}';
</script>
<script src="{% static 'js/base.js' %}"></script>
{% block js %}
{% endblock js %}

main/templates/categories_view.html
{% extends "base.html" %}
{% load static %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/categories_playlists_view.css' %}">
{% endblock css %}

{% block main %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">

        <div class="col col-12 col-lg-4">
            <h2>Categories</h2>
            
            <div class="row add-row">
                <div><i class="fas fa-plus"></i></div>
                <div><input name="category" type="text"></div>
                <div><button type="submit" class="btn btn-primary">Add</button></div>
            </div>

            {% for cat in categories %}
                <div class="category">
                    <div class="row category-row">
                        <div><h4>{{cat}}</h4></div>
                        <div><a class="btn btn-danger btn-sm" href="{% url 'main:category_delete' cat.id  %}"><i class="fas fa-trash"></i></a></div>
                    </div>
                    <ul>
                    {% for file in cat.files.all %}
                        <li>{{ file }}</li>
                    {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>

    </div>
</form>
{% endblock main %}

main/templates/category_delete.html
{% extends "base.html" %}
{% load static %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block main %}
<form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col col-12 col-lg-6" id="file-details">
            Are you sure you want to delete the category {{ category.name }}?
        </div>
    </div>

    <div class="row" id="button-row">
        <input class="btn btn-danger" type="submit" value="Delete"/>
        <button class="btn btn-primary" type="button" onclick="javascript:history.back()">Back</button>
    </div>
</form>
{% endblock main %}

main/templates/file_add.html
{% extends "base.html" %}
{% load static %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/file_add.css' %}">
{% endblock css %}

{% block main %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        
        <div class="col col-12 col-lg-4 thumbnail-container">
            <div class="row thumbnail-row">
                <img id="full-thumbnail" class="full-thumbnail">
            </div>
            <div class="row">
                <input name="thumbnail" id="thumbnail-input" class="btn btn-primary" type="file">
                <div class="col col-12"><button id="upload-thumbnail" class="btn btn-primary" type="button">Upload Thumbnail*</button></div>
                <div class="col col-12 required-text">Required</div>
            </div>
        </div>

        <div class="col col-12 col-lg-3" id="file-details">
            <div class="row file-field">
                <div class="col col-12 field-header">Name*</div>
                <div class="col col-12"><input name="name" id="name" type="text"></div>
                <div class="col col-12 required-text">Required</div>
            </div>
            <div class="row file-field">
                <div class="col col-12 field-header">Categories</div>
                <div class="col col-12">
                    {% for category in categories %}
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="checkbox-{{category}}" name="checkbox-{{category}}" value="{{category}}">
                        <label class="custom-control-label" for="checkbox-{{category}}">{{category}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row file-field">
                <div class="col col-12 field-header">Comment</div>
                <div class="col col-12"><textarea name="comment"></textarea></div>
            </div>
            <div class="row file-field">
                <div class="col col-12" id="filename">{{file.filename}}</div>
                <button id="upload-file" class="btn btn-primary" type="button" >Upload File*</button>
                <input name="file" id="file-input"type="file" class="btn btn-primary">
                <div class="col col-12 required-text">Required</div>
            </div>
        </div>

    </div>

    <div class="row" id="button-row">
        <button id="save-button" class="btn btn-primary" type="button">Save</button>
        <button class="btn btn-primary" type="button" onclick="javascript:history.back()">Back</button>
    </div>
</form>
{% endblock main %}

{% block js %}
    <script src="{% static 'js/file_add.js' %}"></script>
{% endblock js %}

main/templates/file_delete.html
{% extends "base.html" %}
{% load static %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block main %}
<form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col col-12 col-lg-4 thumbnail-container">
            <div class="row thumbnail-row">
                <img class="full-thumbnail" src="{{ file.thumbnail.url }}">
            </div>
        </div>

        <div class="col col-12 col-lg-3" id="file-details">
            Are you sure you want to delete {{ file.name }}?
        </div>
    </div>

    <div class="row" id="button-row">
        <input class="btn btn-danger" type="submit" value="Delete"/>
        <button class="btn btn-primary" type="button" onclick="javascript:history.back()">Back</button>
    </div>
</form>
{% endblock main %}

main/templates/file_view.html
{% extends "base.html" %}
{% load static %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/file_view.css' %}">
{% endblock css %}

{% block main %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="saved-row" class="row">
        {% if saved %}
        <div id="saved-text" class="col">Saved</div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col col-12 col-lg-4 thumbnail-container">
            <div class="row thumbnail-row">
                <img id="full-thumbnail" class="full-thumbnail" src="{{file.thumbnail.url}}">
            </div>
            <div class="row">
                <input name="thumbnail" id="thumbnail-input" type="file" class="btn btn-primary" value="{{file.file.value}}">
                <button class="btn btn-primary" id="upload-thumbnail" type="button">Upload Thumbnail*</button>
            </div>
        </div>

        <div class="col col-12 col-lg-3" id="file-details">
            <div class="row file-field">
                <div class="col col-12 field-header">Name*</div>
                <div class="col col-12"><input name="name" id="name" type="text" value="{{file.name}}"></div>
                <div class="col col-12 required-text">Required</div>
            </div>
            <div class="row file-field">
                <div class="col col-12 field-header">Categories<br></div>
                <div id="checkboxes" class="col col-12">
                    {% for category in categories %}
                    <div class="custom-control custom-checkbox">
                        <input
                            type='hidden'
                            id="checkbox-{{category.id}}-hidden"
                            name='checkbox-{{category.id}}'
                        >
                        <input
                            type="checkbox"
                            class="custom-control-input"
                            {% if category in file.categories.all %} checked="checked" {% endif %}
                            id="checkbox-{{category.id}}"
                            name="checkbox-{{category.id}}"
                            value="{{category.id}}"
                        >
                        <label class="custom-control-label" for="checkbox-{{category.id}}">{{category}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row file-field">
                <div class="col col-12 field-header">Comment</div>
                <div class="col col-12"><textarea name="comment">{{file.comment}}</textarea></div>
            </div>
            <div class="row file-field">
                <div class="col col-12 field-header">File</div>
                <div class="col col-12" id="filename">{{file.filename}}</div>
                <input name="file" id="file-input" type="file" class="btn btn-primary">
                <button class="btn btn-primary" type="button" id="upload-file">Upload File*</button>
            </div>
        </div>

        <div class="col col-12 col-lg-4">
            <div class="row file-field">
                <div class="col col-12 field-header">File size</div>
                <div class="col col-12" id="filesize">{{file.file.size|filesizeformat}}<br></div>
            </div>
            <div class="row file-field">
                <div class="col col-12 field-header">File type</div>
                <div class="col col-12" id="filetype">{{file.filetype}}</div>
            </div>
        </div>

        <div class="col col-12 col-lg-1">
            <a href="{% url 'main:file_delete' file.id  %}" class="button btn btn-danger"><i class="fas fa-trash"></i></a>
        </div>
    </div>

    <div class="row" id="button-row">
        <button id="save-button" class="btn btn-primary" type="button">Save</button>
        <button class="btn btn-primary" type="button" onclick="javascript:history.back()">Back</button>
    </div>
</form>
{% endblock main %}

{% block js %}
    <script src="{% static 'js/file_view.js' %}"></script>
{% endblock js %}

main/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock css %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block main %}
    <div class="row">
    {% for file in files %}
        <div class="col col-12 col-lg-6 file-block" >
            <a href="{% url 'main:file_view' file.id  %}">
                <div class="row">
                    <img class="thumbnail" src="{{ file.thumbnail.url }}">
                    <div class="col row details-container">
                        <div class="col col-12 file-name">
                            {{ file.name }}
                        </div>
                        <div class="col col-12">
                            <div>Categories:</div>
                            {% if file.categories.count %}
                                {{ file.categories.all|join:", " }}
                            {% else %}
                                None
                            {% endif %}
                        </div>
                        <div class="col col-12">
                            <div>Comment:</div>
                            {{ file.comment }}
                        </div>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
    </div>
{% endblock main %}

main/templates/main_topbar.html
<div class="col col-12 col-lg-1">
    <a href="{% url 'main:home' %}" class="topbar-item"><div><i class="fas fa-home"></i></div></a>
</div>
<div class="col col-12 col-lg-2">
    <a href="{% url 'main:file_add' %}" class="topbar-item"><div><i class="fas fa-plus-circle"></i>Add Media File</div></a>
</div>
<div class="col col-12 col-lg-2">
    <a href="{% url 'main:categories_view' %}" class="topbar-item"><div><i class="fas fa-list"></i>View Categories</div></a>
</div>
<div class="col col-12 col-lg-2">
    <a href="{% url 'main:playlists_view' %}" class="topbar-item"><div><i class="fas fa-list"></i>View Playlists</div></a>
</div>
<div class="col col-12 col-lg-3">
    <div>
        <form method="GET" action="{% url 'main:search' %}" id="search-form">
            {% csrf_token %}
            <a href="#"><i class="fas fa-search" id="search-icon"></i></a>
            <input type="search" name="q" id="search-bar" placeholder="Search">
        </form>
    </div>
</div>
<div class="col col-12 col-lg-1">
    <input name="json-upload" id="json-upload" class="btn btn-primary" type="file">
    <div class="col col-12">
        <button id="json-upload-button" class="btn btn-primary btn-sm">Import JSON</button>
    </div>
</div>
<div class="col col-12 col-lg-1">
    <input name="json-download" id="json-download" class="btn btn-primary" type="file">
    <div class="col col-12"><a href="{% url 'main:json' %}"" class="btn btn-primary btn-sm">Export JSON</a></div>
</div>

main/templates/playlist_delete.html
{% extends "base.html" %}
{% load static %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block main %}
<form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col col-12 col-lg-6" id="file-details">
            Are you sure you want to delete the playlist {{ playlist.name }}?
        </div>
    </div>

    <div class="row" id="button-row">
        <input class="btn btn-danger" type="submit" value="Delete"/>
        <button class="btn btn-primary" type="button" onclick="javascript:history.back()">Back</button>
    </div>
</form>
{% endblock main %}

main/templates/playlists_view.html
{% extends "base.html" %}
{% load static %}

{% block topbar %}
    {% include 'main_topbar.html' %}
{% endblock topbar %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/categories_playlists_view.css' %}">
{% endblock css %}

{% block main %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="playlists" class="row">

        <div class="col col-12 col-lg-4">
            <h2>Playlists</h2>
            
            <div class="row add-row">
                <div><i class="fas fa-plus"></i></div>
                <div><input name="playlist" type="text"></div>
                <div><button type="submit" class="btn btn-primary">Add</button></div>
            </div>
            <div class="row arrow-row">
                <i class="fas fa-arrow-down"></i>
                <div>Click on a playlist to see what's in it</div>
            </div>
            
            {% for playlist, data in playlist_data.items %}
                <div class="row playlist-row">
                    <div class="playlist-name col">
                        <a href="#" @click=changePlaylist><h4>{{playlist}}</h4></a>
                    </div>
                    <div class="col col-2"><a class="btn btn-primary btn-sm" href="{% url 'main:playlist_view' data.id  %}"><i class="fas fa-pencil-alt"></i></a></div>
                    <div class="col col-2"><a class="btn btn-danger btn-sm" href="{% url 'main:playlist_delete' data.id  %}"><i class="fas fa-trash"></i></a></div>
                </div>
            {% endfor %}
        </div>

        <div id="playlist-view" class="col col-12 col-lg-8">

            <h3>[[playlist.name]]</h3>

            <div v-if="playlist.files && playlist.files.length">

                <div v-for="p in playlist.files" class="media-file row">
                    <div class="col col-3"><img v-bind:src="[[p.thumbnail]]" class="thumbnail"></div>
                    <div class="col col-3">[[p.name]]</div>
                    <div class="col">[[p.comment]]</div>
                </div>
                
            </div>
            <div v-else>
                <div>No files</div>
            </div>

        </div>
    </div>

</form>
{% endblock main %}

{% block js %}
    <!-- vue.js -->
    <script src="{% static 'js/vue.js' %}"></script>
    <script type='text/javascript'>
        var playlist_data = {{playlist_data|safe}};
    </script>

    <script src="{% static 'js/playlists_view.js' %}"></script>
{% endblock js %}